### ISSUE TITLE
Support for pipeline resolvers

### ISSUE THREAD

**Issue by ntrp** [aheissenberger/serverless-appsync-offline#23]
I am not sure if already supported but currently it does not seem to work.

```
    mappingTemplates:
      - dataSource: Messages
        type: Query
        field: getMessages
        request: "Query.getMessages-req.vtl"
        response: "Query.getMessages-res.vtl"
      - dataSource: Messages
        type: Query
        field: getMessage
        request: "Query.getMessage-req.vtl"
        response: "Query.getMessage-res.vtl"
      - type: Mutation
        field: createMessage
        request: "Wrap-req.vtl"
        response: "Wrap-res.vtl"
        kind: PIPELINE
        functions:
          - authFunction
          - createMessageFunction
    functionConfigurations:
      - dataSource: Auth
        name: authFunction
        request: "Auth-req.vtl"
        response: "Auth-res.vtl"
      - dataSource: Messages
        name: createMessageFunction
        request: "Mutation.createMessage-req.vtl"
        response: "Mutation.createMessage-res.vtl"
```
This is my configuration and it work online but not offline. The error is:
```
{
  "errors": [
    {
      "message": "Cannot read property 'name' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createMessage"
      ]
    }
  ],
  "data": null
}
```
Is it supposed to work? If not is there a plan on supporting it? If any other information is needed please let me know!
