### ISSUE TITLE
Not using merged arrays from config file

### ISSUE THREAD

**Issue by theoribeiro** [aheissenberger/serverless-appsync-offline#27]
This plugin is not using the full potential of appsync-emulator or appsync-plugin when it comes to merging an array of files in Mapping Templates. For example, if I have the following configuration: 
```
  mappingTemplates:
    - ${file(notification-templates.yml)}
    - ${file(user-templates.yml)}
```
Appsync-emulator will resolve it properly and so will appsync-plugin. This is done by the loadServerlessConfig function in Appsync-emulator that is ignored when appsync-offline builds the server since it calls createServer passing this.serverless, instead of passing the path to the Serverless config file. 

Here is how appsync-emulator calls it's own createServer function on `bin/server.js`
```
const serverless = path.join(path.dirname(pkgPath), 'serverless.yml');
const server = await createServer({ wsPort, serverless, port, dynamodb });
```

Because of this call, appsync-emulator calls loadServerlessConfig:
```
  if (typeof serverless === 'object') {
    serverlessConfig = serverless.service;
    serverlessDirectory = serverless.config.servicePath;
  } else {
    serverlessDirectory =
      typeof serverless === 'string'
        ? path.dirname(serverless)
        : findServerlessPath();
    const config = await loadServerlessConfig(serverlessDirectory); // This is called
    serverlessConfig = config.config;
  }
```

loadServerlessConfig does the flattening of the arrays:
```
const output = {
    config: {
      ...config,
      custom: {
        ...custom,
        appSync: {
          ...appSync,
          mappingTemplates: flatten(mappingTemplates),
          dataSources: flatten(dataSources),
        },
      },
      resources: normalizeResources(config),
    },
    directory: cwd,
  };
```

In order to avoid having to do the same in appsync-offline, I suggest simply calling appsync-emulator's createServer in the same way it calls itself. This would support the use case that both the other two plugins in this ecosystem support. 

Does all this make sense? I can create a PR if you are willing to take this suggestion. 

--Theo

**Comment by aheissenberger** [comment]
@theobribeiro I am happy to accept a PR which keeps this plugin in sync with AppSync emulator

**Comment by aheissenberger** [comment]
@theoribeiro I still would appreciate to accept a PR for this change as you have a good test case :-)

**Comment by aheissenberger** [comment]
@theoribeiro  I did look into this and do not see your problem. All Serverless variables are resolved by the Serverless framework before a hook is called:
https://serverless.com/framework/docs/providers/aws/guide/plugins/#serverless-instance

I tested & debugged this with the following configuration:

serverless.yml
```yml
    mappingTemplates:
      - dataSource: NotesTableDS
        type: Query
        field: allNotes
        request: "allnotes-request.vtl"
        response: "allnotes-response.vtl"
      - ${file(mappingTemplateGetNote.yml)}
```

mappingTemplateGetNote.yml
```yml
dataSource: NotesTableDS
type: Query
field: getNote
request: "getnote-request.vtl"
response: "common-response.vtl"
```

when I start local with:
`sls offline`

everything is resolved.

Using `https://github.com/ConduitVC/aws-utils/blob/1149ebdf2e73d15d358afab1abe39957aa115073/packages/appsync-emulator-serverless/loadServerlessConfig.js` is not an option as it is a hack for the use case of using the emulator without the Serverless framework.
