### ISSUE TITLE
ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by mhrisse** [aheissenberger/serverless-appsync-offline#28]
Hi!

First of all thanks for doing this project, 
well done.

We are setting up `serverlesss-appsync-offline` and only want to use lambdas as datasource. 

I read the docs, but unfortunately I cannot find any simple example with serverless and lambda on the web to get us started. If you can help us out with this issue, we will happily contribute this back here. @aheissenberger 

However we have run into the following problem:

**terminal output:**
```
$ sls appsync-offline start
Serverless: AppSync Standalone
Serverless: dynamoDB started: http://localhost:8000/
Serverless: ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
```

with no working endpoint and the `ERROR` above.

or

```
$ sls offline
Serverless: Starting Offline: dev/us-west-2.

Serverless: Routes for graphql:
Serverless: (none)

Serverless: Offline listening on http://localhost:3000
```

with no route for graphql, respectively.

**serverless.yml:**

```
service: XXXXXXX-api

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev

plugins:
plugins:
  - serverless-dynamodb-local
  - serverless-appsync-plugin
  - serverless-appsync-offline
  - serverless-offline

functions:
  graphql:
    handler: handler.graphqlHandler

custom:
  appSync:
    name:  XXXXXXX-${self:provider.stage}-serverless
    region: ${self:provider.region}
    serviceRole: "${self:service.name}-AppSyncServiceRole"
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW
      userPoolId: ********************
    mappingTemplatesLocation: # defaults to mapping-templates
    mappingTemplates:
      - type: Query
        dataSource: LambdaSource
        field: getPatients
        request: "query-getpatients-request.vtl"
        response: "common-response.vtl"
    dataSources:
      - type: AWS_LAMBDA
        name: LambdaSource
        description: "Lambda DataSource"
        config:
          functionName: graphql
          lambdaFunctionArn: { Fn::GetAtt: [GraphqlLambdaFunction, Arn] }
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }
  appsync-offline:
    port: 62222
    dynamodb:
      server:
        port: 8000

resources:
  - ${file(resources/appsync.yml)}
```

**schema.graphql**:
```
type Patient {
  id: ID!
  name: String!
}

type Query {
  getPatients: [Patient]
}
```

Any pointers very much appreciated!
