### ISSUE TITLE
Connect to remote dynamoDB with Arn

### ISSUE THREAD

**Issue by sean7218** [aheissenberger/serverless-appsync-offline#34]
```
  appsync-offline:
    port: 62222
    dynamodb:
      client:
        endpoint: "http://localhost:8000"
        region: us-east-1
        accessKeyId: "SDKFHKJSDKJHFSKDHFS"
        secretAccessKey: "SLDKJFSLKDFJSLDKFJLKSDFJ"
```

can the endpoint to be ARN for the dynamodb? instead of using offline dynamodb?

**Comment by sean7218** [comment]
```
custom:
  appsync-offline:
    port: 62222
    dynamodb:
      client:
        endpoint: "https://dynamodb.us-east-1.amazonaws.com"
        region: us-east-1
        accessKeyId: SDFSFSDFDFDSFSDFSDF
        secretAccessKey: SDFSDFSDFSDFSDDSF
```

thank you, i figured out the way to connect to remote dynamodb
