### ISSUE TITLE
Can't change schema file location.

### ISSUE THREAD

**Issue by zhaoyi0113** [aheissenberger/serverless-appsync-offline#48]
I define my `schema.graphql` file under `./schema` directory. On my `serverless.yml` file, it has 

```
custom:
   appsync:
      name: ${self:provider.stackName}
      schema: 
         - ./schema/device.graphql
         - ./schema/schema.graphql
         - ./schema/transaction.graphql
         - ./schema/identity.graphql
```

when I run `sls appsync-offline start`, I got this error:

```
Serverless: AppSync Standalone
Serverless: dynamoDB started: http://localhost:62224/
Serverless: ERROR: Error: schema file: /Users/apps/schema.graphql must exist
```

It seems that it always look for `schema.graphql` under project root directory.
